openapi: 3.0.0
info:
  title: API de reserva de salas
  version: 1.0.0
  description: API REST para la gestión de reserva de salas de una biblioteca ficticia
servers:
  - url: http://localhost:3000
    description: Servidor de desarrollo

paths:
  /reservations:
    get:
      summary: Obtener todas las reservas
      description: Devuelve todas las reservas activas del sistema.
      tags: [Reservas]
      responses:
        "200":
          description: Lista de reservas activas en el sistema
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Booking"

    post:
      summary: Crear una nueva reserva
      description: Registra una nueva reserva si cumple con las reglas de negocio.
      tags: [Reservas]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Booking"
      responses:
        "201":
          description: Reserva creada correctamente
        "400":
          description: Error en la validación o conflicto

  /reservations/{id}:
    get:
      summary: Obtener una reserva por ID
      description: Devuelve los detalles de una reserva específica.
      tags: [Reservas]
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Reserva encontrada
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Booking"
        "404":
          description: Reserva no encontrada

    put:
      summary: Actualizar una reserva existente
      description: Modifica una reserva ya registrada.
      tags: [Reservas]
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Booking"
      responses:
        "200":
          description: Reserva actualizada correctamente
        "404":
          description: Reserva no encontrada

    delete:
      summary: Eliminar una reserva
      description: Elimina una reserva existente del sistema.
      tags: [Reservas]
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Reserva eliminada correctamente
        "404":
          description: Reserva no encontrada

components:
  schemas:
    Booking:
      type: object
      required: [id, roomId, user, time, people]
      properties:
        id:
          type: string
        roomId:
          type: string
        user:
          type: string
        time:
          type: string
          format: date-time
        people:
          type: integer
